[project]
name = "python-template"
version = "1"
requires-python = ">3.12"
dependencies = [
    ]

[project.optional-dependencies]
dev = [
    ]

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.ruff]
line-length = 120
src = ["src"]

[tool.mypy]
python_version = "3.12"
